# Generated by Django 3.0.2 on 2020-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
