# Generated by Django 3.0.2 on 2020-05-08 09:44

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courses_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_title', models.CharField(max_length=50)),
                ('v_category', models.CharField(max_length=50)),
                ('v_desc', models.CharField(default='', max_length=500)),
                ('v_video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
