# Generated by Django 3.0.2 on 2020-05-08 15:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='v_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
