# Generated by Django 3.0.2 on 2020-05-08 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200508_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='pubDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='v_pubDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
